* Clicking on a compilation error opens a new window

Context: editing go. To reproduce:

- simulate a compilation error
- open project vterm
- build the project
- click on the error

Expected: the error is opened in the main window already displaying go code

Actual: a new window is opened to show the error

* Improve Go treesitter navigation

C-M-n and C-M-p still do not work great; the n one gets stuck. Try a larger Go file.

* Try vertico unobtrusive

vertico-unobtrusive-mode seems to stay out of the way more now that we learned how to use it.

* Try shift-text package

shift-text-up and shift-text down have to be useful.
Possibly this one actually: https://github.com/emacsfodder/move-text

* Bind M-n, M-p

* Kill current line and select current line

* Consider puni

Might be a good replacement for paredit:
https://github.com/AmaiKinono/puni#what-is-it

* Improve xref-find-apropos

This is useful but does not have the same UX polish as VS Code. There could be a consult package
around it.
