* t0yv0-emacs

Personal Emacs config.

** How do you use Emacs?

I came to Emacs for an esolang (Coq, OCaml, Haskell) IDE but am staying for a nice and stable text editing platform. As
of 2024, I use Emacs daily for:

- developing code in Go and TypeScript
- keeping scratchpads and daily notes in Org
- accumulating reference notes in Org-roam

I occasionally enjoy the instant gratification of coding up tiny extensions in Elisp

I mostly use a Mac OS base system these days, but have used both Linux and Windows in the past.

** Why is this public

No good answer here, only "why not?" spirit. I occasionally get a "you're holding it wrong" comment from the Emacs
community watching me struggle or reinvent wheels. I do enjoy this. But in the end I am an incorrigible autodidact
determined to go at my own slow pace. Emacs and my habits around it provide an island of stability in the churning
waters of tech.

** Why does this use Nix?

I find it valuable to opt out of updates on the base C or Node-based packages (i.e. mermaid-cli) to avoid my setup from
being broken when I need stability. Nix seems very suitable for this particular job.

** What can I use?

I expect there is not much of interest in this repo for reuse purposes. I move Elisp experiments that last a few years
to separate repos, perhaps some of these can be of general interest:

- [[https://github.com/t0yv0/gh-autolinks.el][gh-autolinks.el]]
- [[https://github.com/t0yv0/testrun.el][testrun.el]]
- [[https://github.com/t0yv0/treesitedit.el][treesitedit.el]]
- [[https://github.com/t0yv0/vterms.el][vterms.el]]

** Contact

Drop me a note on Mastodon ([[https://vmst.io/@t0yv0][t0yv0]]).
